### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by takano-hi** [midwhite/QuizMaster#1]
## Set up
- [x] init project as API Mode
- [x] enable to connect DB
- [x] enable to run server for development
- [x] setup cors
- [x] setup timezone
- [x] enable to use i18n
- [x] set up rspec

### application layer
- [x] enable user authentication
- [x] enable to sign in user

### service layer
- [x] generate models and migrations
- [x] generate controllers
- [x] enable to create quizzes
- [x] enable to update quizzes
- [x] enable to get quizzes
- [ ] enable to search quizzes
- [x] enable to delete quizzes

### Unit Test
- [x] User model
- [x] Quiz model

### Integration Test
- [x] users request
- [x] quizzes request

## check before release
- [x] list environment variables required to build application
- [x] write README.md
- [x] pass all the tests

## future
- [ ] enable to make test as quiz group
- [ ] enable to search quizzes with subject categories
